import * as React from "react";

export const X_URL = "https://x.com/uisuleman";
const UPDATED = "September 26, 2026";

function LegalLayout({ title, intro, children }: { title: string; intro: string; children: React.ReactNode }) {
  return (
    <article className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24">
      <p className="text-sm font-medium text-fg-subtle">Legal</p>
      <h1 className="mt-2 text-4xl font-semibold tracking-tight text-fg">{title}</h1>
      <p className="mt-3 text-sm text-fg-subtle">Last updated {UPDATED}</p>
      <p className="mt-8 text-lg text-fg-muted">{intro}</p>
      <div className="mt-12 space-y-10 [&_a]:font-medium [&_a]:text-fg [&_a]:underline [&_a]:underline-offset-4 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-fg [&_li]:pl-1 [&_p]:text-base [&_p]:text-fg-muted [&_section>*+*]:mt-3 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-5 [&_ul]:text-base [&_ul]:text-fg-muted">
        {children}
      </div>
    </article>
  );
}

export function Privacy() {
  return (
    <LegalLayout title="Privacy Policy" intro="Promptline UI is a static documentation site for a free, open-source component library. It has no accounts, no forms and no tracking — this page explains the little data that is involved.">
      <section>
        <h2>What we collect</h2>
        <p>Nothing directly. The site does not ask for your name, email or any other personal information, and it does not use analytics, advertising or tracking cookies.</p>
      </section>
      <section>
        <h2>Hosting</h2>
        <p>The site is hosted on Vercel. Like any web host, Vercel processes basic technical data — such as your IP address, browser type and the pages requested — to deliver the site and keep it secure. See <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer">Vercel's privacy policy</a>.</p>
      </section>
      <section>
        <h2>Fonts</h2>
        <p>Fonts are loaded from Google Fonts, so your browser connects to Google's servers when a page loads. See <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Google's privacy policy</a>.</p>
      </section>
      <section>
        <h2>Local storage</h2>
        <p>Some interactive demos may save small preferences (for example, a dismissed banner) in your browser's local storage. This stays on your device and is never sent to us. Clearing your browser data removes it.</p>
      </section>
      <section>
        <h2>Using the components</h2>
        <p>When you install components with the shadcn CLI, the MCP server or a copied prompt, the code is downloaded to your project. We don't receive information about your project or how you use the code.</p>
      </section>
      <section>
        <h2>External links</h2>
        <p>The site links to other services such as GitHub and X. Their own privacy policies apply once you leave this site.</p>
      </section>
      <section>
        <h2>Changes</h2>
        <p>If this policy changes, the updated version will be posted here with a new date.</p>
      </section>
      <section>
        <h2>Contact</h2>
        <p>Questions? Reach out on X at <a href={X_URL} target="_blank" rel="noreferrer">@uisuleman</a>.</p>
      </section>
    </LegalLayout>
  );
}

export function Terms() {
  return (
    <LegalLayout title="Terms of Service" intro="These terms cover your use of the Promptline UI website and the components published on it. By using the site, you agree to them.">
      <section>
        <h2>The components</h2>
        <p>The component source code is released under the MIT License. You may use, copy, modify and distribute it in personal and commercial projects, including client work, as long as the license notice is kept with substantial portions of the code.</p>
      </section>
      <section>
        <h2>The website</h2>
        <p>The website itself — its design, writing, the Promptline UI name and logo — is © Promptline UI. Please don't copy the site or present it as your own, or use the name and logo in a way that suggests endorsement.</p>
      </section>
      <section>
        <h2>Acceptable use</h2>
        <ul>
          <li>Don't attempt to disrupt, overload or gain unauthorized access to the site or its hosting.</li>
          <li>Don't use automated tools to scrape the site in a way that degrades it for others. Using the registry, llms.txt and the shadcn MCP server as intended is welcome.</li>
        </ul>
      </section>
      <section>
        <h2>AI tools</h2>
        <p>The site offers prompts and registry files for AI assistants. Output generated by third-party AI tools is outside our control — review generated code before you ship it.</p>
      </section>
      <section>
        <h2>No warranty</h2>
        <p>The site and components are provided "as is", without warranty of any kind. You are responsible for testing the components in your product, including for accessibility, security and legal requirements that apply to you.</p>
      </section>
      <section>
        <h2>Limitation of liability</h2>
        <p>To the extent permitted by law, Promptline UI and its author are not liable for any damages arising from the use of the site or the components.</p>
      </section>
      <section>
        <h2>Changes</h2>
        <p>These terms may be updated from time to time. Continued use of the site after an update means you accept the new terms.</p>
      </section>
      <section>
        <h2>Contact</h2>
        <p>Questions? Reach out on X at <a href={X_URL} target="_blank" rel="noreferrer">@uisuleman</a>.</p>
      </section>
    </LegalLayout>
  );
}
