import fs from "fs";
const ui = fs.readdirSync("src/components/ui").filter((f) => f.endsWith(".tsx") && f !== "primitives.tsx").map((f) => `export * from "./components/ui/${f.replace(".tsx", "")}";`);
const ai = fs.readdirSync("src/components/ai").filter((f) => f.endsWith(".tsx")).map((f) => `export * from "./components/ai/${f.replace(".tsx", "")}";`);
fs.writeFileSync("src/index.ts", ["// Generated by scripts/gen-index.mjs", ...ui, ...ai, 'export { cn } from "./lib/cn";', 'export * from "./lib/hooks";', 'export * from "./lib/floating";', ""].join("\n"));
